### ISSUE TITLE
   Error: Cannot find module 'xml2js'

### ISSUE THREAD

**Issue by nloui** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#150] opened 2016-06-02 20:04 UTC
Getting this error when Meteor Cordova is compiling... 

Checking dependencies:

    Can't find module mkpath, running npm install

=> Errors executing Cordova commands:

   While preparing Cordova project for platform iOS:

   Error: Cannot find module 'xml2js'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at

**Comment by nloui** [comment] 2016-06-02 20:21
Little more digging - installed these modules manually and now getting

   The following build commands failed:
   CompileC
   build/myproject.build/Debug-iphonesimulator/myproject.build/Objects-normal/i386/BranchSDK.o
   myproject/Plugins/io.branch.sdk/BranchSDK.m normal i386 objective-c
   com.apple.compilers.llvm.clang.1_0.compiler
   CompileC
   build/myproject.build/Debug-iphonesimulator/myproject.build/Objects-normal/i386/AppDelegate+BranchSdk.o
   myproject/Plugins/io.branch.sdk/AppDelegate+BranchSdk.m normal i386
   objective-c com.apple.compilers.llvm.clang.1_0.compiler
   (2 failures)
   Error code 65 for command: xcodebuild with args:
   -xcconfig,/Users/myusername/Documents/myproject/app/.meteor/local/cordova-build/platforms/ios/cordova/build-debug.xcconfig,-project,myproject.xcodeproj,ARCHS=i386,-target,myproject,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/myusername/Documents/myproject/app/.meteor/local/cordova-build/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/myusername/Documents/myproject/app/.meteor/local/cordova-build/platforms/ios/build/sharedpch
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

**Comment by renesansz** [comment] 2016-06-02 21:49
Hey @nloui , Will checkout the said error, I guess this happened when I have updated the iOS library.
Will get back to you for fix.

**Comment by renesansz** [comment] 2016-06-03 03:00
@nloui , just found out that you have a related error on issue #139 .
Please see the solution. thanks!

**Comment by nloui** [comment] 2016-06-03 05:23
Thanks, just took a look at that and pulled the latest but still having the same issue unfortunately

**Comment by renesansz** [comment] 2016-06-03 10:21
@nloui , no prob. I've Submitted PR for this, we'll just wait for this to be merged #151

**Comment by renesansz** [comment] 2016-06-13 05:29
@nloui let me know if this issue is resolved. thanks 👌

**Comment by nloui** [comment] 2016-06-14 03:33
@renesansz as of the latest commit, still not working

**Comment by renesansz** [comment] 2016-06-15 22:44
@nloui : I see, can you do a re-installation of the installed platforms and plugins just to check if it's not caused by some old build cache. Also can you verify if there are some of your plugins is having a build conflict with Branch? I apologise that I'm really getting a hard time to determine the cause of the issue, as I thought from my submitted PR it is caused by some missing headers in the `plugin.xml`.

**Comment by renesansz** [comment] 2016-07-03 12:22
@nloui ,
Just wanted to know if my solution fixed the issue?

**Comment by nloui** [comment] 2016-07-03 15:46
@renesansz been traveling, let me try it out and let you know

**Comment by nloui** [comment] 2016-07-03 17:23
@renesansz  Latest version of the code appears to be working.  Compiles and doesn't crash... now just need to get it configured to start to see data come through

**Comment by renesansz** [comment] 2016-07-04 14:36
@nloui , I guess the compilation issue is now resolved, will close the ticket now.
If there is another error with the plugin please don't hesitate to create another issue.

Thanks!

**Closed by renesansz** 2016-07-04 14:36 UTC
