### ISSUE TITLE
iOS - Builds still failing (2.0.5)

### ISSUE THREAD

**Issue by gabaum10** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#73] opened 2016-03-17 13:46 UTC
Guys, my builds are _still_ failing.  I thought this issue was fixed?  I'm using version 2.0.5 from NPM.  

CompileC build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/BranchSDK.o Veoci\ -\ DEV/Plugins/io.branch.sdk/BranchSDK.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd .../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents.../Platforms/iPhoneOS.platform.../usr/bin:/Applications/Xcode.app/Contents.../usr/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools:/platform-tools"
    /Applications/Xcode.app/Contents.../Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -gmodules -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents.../Platforms/iPhoneOS.platform.../SDKs/iPhoneOS9.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote .../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Veoci\ -\ DEV-generated-files.hmap -I.../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Veoci\ -\ DEV-own-target-headers.hmap -I.../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Veoci\ -\ DEV-all-target-headers.hmap -iquote .../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Veoci\ -\ DEV-project-headers.hmap -I.../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/build/device/include -I.../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/build/device/usr/local/lib/include -I.../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/build/UninstalledProducts/include -I.../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/build/device -I.../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/DerivedSources/armv7 -I.../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/DerivedSources -F.../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/build/device -include .../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/build/sharedpch/Veoci\ -\ DEV-Prefix-aooswzgffdjakkabtibdsuigiqoe/Veoci\ -\ DEV-Prefix.pch -MMD -MT dependencies -MF .../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/BranchSDK.d --serialize-diagnostics .../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/BranchSDK.dia -c .../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/Veoci\ -\ DEV/Plugins/io.branch.sdk/BranchSDK.m -o .../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/BranchSDK.o
In file included from .../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/Veoci - DEV/Plugins/io.branch.sdk/BranchSDK.m:8:
.../builds/build.2016-03-17.09-43-01.wWaLGO.tmp/Veoci_Dev/platforms/ios/Veoci - DEV/Plugins/io.branch.sdk/BranchSDK.h:8:9: fatal error: 'Branch/Branch.h' file not found
#import <Branch/Branch.h>
        ^
1 error generated.

**Comment by harshabonthu** [comment] 2016-03-17 13:54
@gabaum10  I guess npm update with fix wasn't released yet. 

FIx for your issue would be goto `Plugins/io.branch.sdk/BranchSDK.h` and change `#import 'Branch/Branch.h'`  to `#import 'Branch.h'`

**Comment by gabaum10** [comment] 2016-03-17 14:58
I would if I could, but I've switched over to building through Intel XDK because I don't have access to a mac.  Modifying the plugin source files currently is not supported by them.  It pulls the files fresh from NPM every build.  I have to wait until the fix is pushed there.  

I could have sworn @aaustin said it was fixed in https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/issues/71, but it's stil not working.  The version in NPM is 2.0.5 as per: https://www.npmjs.com/package/branch-cordova-sdk

**Comment by aaustin** [comment] 2016-03-17 15:10
I definitely fixed the header so that it'd be `#import 'Branch.h'` for 2.0.5. Perhaps you need to delete and re-install? Let me bump to 2.0.6 and do it again to be 1000% sure.

**Comment by aaustin** [comment] 2016-03-17 15:19
Deployed again, with the header definitely changed. I have to change it back before committing since we're using the framework for the git repo.

**Comment by gabaum10** [comment] 2016-03-17 15:28
I verified the code being sent with the build.  That now looks right.  Unfortunately, there are a bunch of other errors now.  Does this actually work when you guys test it?  Am I doing something wrong?

I see two errors now:

CompileC build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/BranchSDK.o Veoci\ -\ DEV/Plugins/io.branch.sdk/BranchSDK.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd .../Veoci_Dev/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents.../Platforms/iPhoneOS.platform.../usr/bin:/Applications/Xcode.app/Contents.../usr/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools:/platform-tools"
    /Applications/Xcode.app/Contents.../Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -gmodules -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents.../Platforms/iPhoneOS.platform.../SDKs/iPhoneOS9.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote .../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Veoci\ -\ DEV-generated-files.hmap -I.../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Veoci\ -\ DEV-own-target-headers.hmap -I.../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Veoci\ -\ DEV-all-target-headers.hmap -iquote .../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Veoci\ -\ DEV-project-headers.hmap -I.../Veoci_Dev/platforms/ios/build/device/include -I.../Veoci_Dev/platforms/ios/build/device/usr/local/lib/include -I.../Veoci_Dev/platforms/ios/build/UninstalledProducts/include -I.../Veoci_Dev/platforms/ios/build/device -I.../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/DerivedSources/armv7 -I.../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/DerivedSources -F.../Veoci_Dev/platforms/ios/build/device -include .../Veoci_Dev/platforms/ios/build/sharedpch/Veoci\ -\ DEV-Prefix-aeiknbvxqnglcncwjfppntussout/Veoci\ -\ DEV-Prefix.pch -MMD -MT dependencies -MF .../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/BranchSDK.d --serialize-diagnostics .../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/BranchSDK.dia -c .../Veoci_Dev/platforms/ios/Veoci\ -\ DEV/Plugins/io.branch.sdk/BranchSDK.m -o .../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/BranchSDK.o
In file included from .../Veoci_Dev/platforms/ios/Veoci - DEV/Plugins/io.branch.sdk/BranchSDK.m:8:
.../Veoci_Dev/platforms/ios/Veoci - DEV/Plugins/io.branch.sdk/BranchSDK.h:9:9: fatal error: 'Branch/BranchLinkProperties.h' file not found
#import "Branch/BranchLinkProperties.h"
        ^
1 error generated.

CompileC build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/AppDelegate+BranchSdk.o Veoci\ -\ DEV/Plugins/io.branch.sdk/AppDelegate+BranchSdk.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd .../Veoci_Dev/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents.../Platforms/iPhoneOS.platform.../usr/bin:/Applications/Xcode.app/Contents.../usr/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools:/platform-tools"
    /Applications/Xcode.app/Contents.../Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -gmodules -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents.../Platforms/iPhoneOS.platform.../SDKs/iPhoneOS9.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote .../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Veoci\ -\ DEV-generated-files.hmap -I.../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Veoci\ -\ DEV-own-target-headers.hmap -I.../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Veoci\ -\ DEV-all-target-headers.hmap -iquote .../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Veoci\ -\ DEV-project-headers.hmap -I.../Veoci_Dev/platforms/ios/build/device/include -I.../Veoci_Dev/platforms/ios/build/device/usr/local/lib/include -I.../Veoci_Dev/platforms/ios/build/UninstalledProducts/include -I.../Veoci_Dev/platforms/ios/build/device -I.../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/DerivedSources/armv7 -I.../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/DerivedSources -F.../Veoci_Dev/platforms/ios/build/device -include .../Veoci_Dev/platforms/ios/build/sharedpch/Veoci\ -\ DEV-Prefix-aeiknbvxqnglcncwjfppntussout/Veoci\ -\ DEV-Prefix.pch -MMD -MT dependencies -MF .../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/AppDelegate+BranchSdk.d --serialize-diagnostics .../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/AppDelegate+BranchSdk.dia -c .../Veoci_Dev/platforms/ios/Veoci\ -\ DEV/Plugins/io.branch.sdk/AppDelegate+BranchSdk.m -o .../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/AppDelegate+BranchSdk.o
.../Veoci_Dev/platforms/ios/Veoci - DEV/Plugins/io.branch.sdk/AppDelegate+BranchSdk.m:10:9: fatal error: 'Branch/Branch.h' file not found
#import <Branch/Branch.h>

**Comment by aaustin** [comment] 2016-03-17 15:34
Looks like there were some hidden spots. Try again? I went through all files now.

**Comment by gabaum10** [comment] 2016-03-17 15:44
Now I'm getting a different error that does not happen if I exclude the plugin:

Ld build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/Veoci\ -\ DEV normal armv7
    cd .../Veoci_Dev/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents.../Platforms/iPhoneOS.platform.../usr/bin:/Applications/Xcode.app/Contents.../usr/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools:/platform-tools"
    /Applications/Xcode.app/Contents.../Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents.../Platforms/iPhoneOS.platform.../SDKs/iPhoneOS9.2.sdk -L.../Veoci_Dev/platforms/ios/build/device -L.../Veoci_Dev/platforms/ios/Veoci\ -\ DEV/Plugins/com.pushwoosh.plugins.pushwoosh -F.../Veoci_Dev/platforms/ios/build/device -filelist .../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/Veoci\ -\ DEV.LinkFileList -miphoneos-version-min=8.0 -dead_strip -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -framework AssetsLibrary .../Veoci_Dev/platforms/ios/build/device/libCordova.a -framework CoreGraphics -framework MobileCoreServices -weak_framework ImageIO -framework CoreLocation -framework AVFoundation -weak_framework SystemConfiguration -weak_framework AudioToolbox .../Veoci_Dev/platforms/ios/Veoci\ -\ DEV/Plugins/com.pushwoosh.plugins.pushwoosh/Pushwoosh -framework Security -framework Storekit -lstdc++ -lz -Xlinker -dependency_info -Xlinker .../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/Veoci\ -\ DEV_dependency_info.dat -o .../Veoci_Dev/platforms/ios/build/Veoci\ -\ DEV.build/Release-iphoneos/Veoci\ -\ DEV.build/Objects-normal/armv7/Veoci\ -\ DEV
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_CSSearchableItem", referenced from:
      objc-class-ref in BranchCSSearchableItemAttributeSet.o
  "_OBJC_METACLASS_$_CSSearchableItemAttributeSet", referenced from:
      _OBJC_METACLASS_$_BranchCSSearchableItemAttributeSet in BranchCSSearchableItemAttributeSet.o

** BUILD FAILED **

Looking around, it seems this is because of the way some of the files are linked?  I have never seen this before, but I'm building via CLI-5.1.1.  Is that not supported by this plugin?  

Not sure if this SO [answer ](http://stackoverflow.com/questions/6429494/undefined-symbols-for-architecture-armv7) helps or not.  I personally have no depth here so I can't be of much help.

**Comment by aaustin** [comment] 2016-03-17 16:06
So, with the update, we required CoreSpotlight.framework. I've asked our contractors to attempt to bundle this into the npm install process, but they haven't done this yet. Can you try added it it/

**Comment by gabaum10** [comment] 2016-03-17 17:18
I have no idea how to do that.  Like I mentioned before, I'm out of my depth here.  I was just hoping to use the plugin for the end goal.  I guess I'll just wait for the real fix to go out.  

Sorry I'm not more helpful fixing this stuff.  Some day I'll learn more about the actual cordova process.

**Comment by harshabonthu** [comment] 2016-03-17 17:36
@aaustin I noticed these frameworks listed in docs, but wasn't sure if the documentation was accurate as the functionality was working without adding them.  

https://dev.branch.io/getting-started/sdk-integration-guide/advanced/ios/#install-the-sdk-manually

**Comment by gabaum10** [comment] 2016-03-17 17:47
So this actually builds using cli-6.0.0, but not cli-5.1.1.  I assume cli-6.0 includes the necessary dependencies as part of the cordova base package.  For policy reasons, I can't use 6.0.0 at the moment.  That's why I am hoping you could package up any dependencies in the package so cli-5.1.1 could be used for production.

**Comment by gabaum10** [comment] 2016-03-21 20:35
I reverted back to my old build process using PGB for now since that supports cli-6.0.0.  I still think this would be a good improvement, but not strictly speaking blocking for me at least.  

Now if I could only figure out how to get universal links working...

**Comment by renesansz** [comment] 2016-03-23 05:30
@gabaum10 I'm trying to replicate the issue. But when I use v5.1.1, nothing happens upon building the app.

**Comment by renesansz** [comment] 2016-03-23 06:21
@gabaum10 , could you try this solution?
http://phonegap.com/blog/2015/06/16/phonegap-updated-on-build/

**Comment by gabaum10** [comment] 2016-03-23 13:12
I just switched over to cli-6.0.0.  It's building fine with that and I'm not going to fight it anymore.  

I was building on Phonegap build using the `<preference name='phonegap-version' value='cli-5.1.1' />` parameter and it was failing.

**Comment by bjornbos** [comment] 2016-06-21 09:50
I'm using Cordova 6.1, but this error still occurs:

fatal error: 'Branch/Branch.h' file not found
1>  #import <Branch/Branch.h>

**Comment by qimingfang** [comment] 2016-06-22 04:14
I'm getting this as well. Could it be due to the new release?

**Comment by renesansz** [comment] 2016-06-22 04:16
@bjornbos @qimingfang ,
I'll gonna take a look on this again, will give you a response once I was able to find the cause of the problem.

**Comment by aaustin** [comment] 2016-06-22 04:17
Hey @qimingfang - The above issue was resolved. You're getting the `Branch.h` not found? Or is it a different error? Also, are you using NPM or the Github repo?

**Comment by qimingfang** [comment] 2016-06-22 04:22
@aaustin i'm also getting `io.branch.sdk/BranchSDK.h:8:9: fatal error: 'Branch/Branch.h' file not found`

I added this through the github link in the README. Didn't realize there was an npm for this. Is this the one? https://tonicdev.com/npm/branch-cordova-sdk

**Comment by aaustin** [comment] 2016-06-22 04:26
Yessir - that's the one. I believe I found your issue, which was a result of me deploying to NPM earlier but not updating the plugin.xml. I've just resolved the github plugin.xml here: https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/commit/0a8ccb0ea93c25960633e360a0ccb4e4aef4d114

**Comment by renesansz** [comment] 2016-06-22 05:10
oh, thanks @aaustin , will re-close the issue now.

**Closed by renesansz** 2016-06-22 05:10 UTC

**Comment by qimingfang** [comment] 2016-06-22 05:52
thanks @aaustin! your fix worked well :) are you planning on bumping the patch version for this fix and upload a new version onto npm?

**Comment by aaustin** [comment] 2016-06-22 16:02
The NPM version is working fine as far as I can tell. I had just mangled the Github one :(
