### ISSUE TITLE
Cannot build - Crashalytics dependency is missing

### ISSUE THREAD

**Issue by quocble** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#156] opened 2016-06-20 22:13 UTC
Crashalytics dependency is gone from Maven? I can't build it anymore

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.crashlytics.sdk.android:answers-shim:0.0.3.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.pom
         https://repo1.maven.org/maven2/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.aar
         file:/Users/quoc/Library/Android/sdk/extras/android/m2repository/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.pom
         file:/Users/quoc/Library/Android/sdk/extras/android/m2repository/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.aar
         file:/Users/quoc/Library/Android/sdk/extras/google/m2repository/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.pom
         file:/Users/quoc/Library/Android/sdk/extras/google/m2repository/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.aar
     Required by:
         :android:unspecified > io.branch.sdk.android:library:1.14.0
```

**Comment by aaustin** [comment] 2016-06-20 22:15
Hey @quocble - We're looking into it. This shouldn't have been an issue. Apologies for the hangup!

**Comment by quocble** [comment] 2016-06-20 22:17
Thanks @aaustin

**Comment by aaustin** [comment] 2016-06-20 23:00
Hey @quocble - The issue is that Fabric's shim is in `jcenter` and not `maven`. Unfortunately, it seems like Cordova doesn't allow you to update the gradle build file to add this in, so I'm updating the plugin.xml file to use the last version of our Android SDK.

**Comment by aaustin** [comment] 2016-06-20 23:01
Here's the commit https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/commit/9f654d125dc361164a58aebe3e7a0aae5b22079a. Are you using NPM?

**Comment by quocble** [comment] 2016-06-20 23:14
@aaustin I used the official instructions pointing to Github. What's the best way to inject in your change? Thanks!

**Comment by aaustin** [comment] 2016-06-21 00:41
I think you'd just need to re-add the module. You might need to uninstall and reinstall it.

**Comment by aaustin** [comment] 2016-06-21 21:36
@quocble I'm going to close this out. I've confirmed the Github version is building fine. Please let me know if you're still struggling!

**Closed by aaustin** 2016-06-21 21:36 UTC
