### ISSUE TITLE
Build failing for iOS

### ISSUE THREAD

**Issue by BorntraegerMarc** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#539] opened 2018-12-11 07:43 UTC
I get the following error when building for iOS:
```
=== BUILD TARGET Komed Health OF PROJECT Komed Health WITH CONFIGURATION Debug ===

Check dependencies
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.

The following build commands failed:
	Check dependencies
** ARCHIVE FAILED **

```

I'm guessing this plugin specifies an outdated Swift version? I'm building with XCode 10+ and I specified the swift version as 3.0 in my project.

**Comment by csalmi-branch** [comment] 2019-01-15 21:54
@BorntraegerMarc We believe that it is likely being caused by this known issue in Cordova:
https://github.com/akofman/cordova-plugin-add-swift-support/issues/47

We are still looking into it though, and trying to confirm the root cause.

**Comment by csalmi-branch** [comment] 2019-01-16 23:30
@BorntraegerMarc Could you see if the fix (or other workarounds) listed in that known Cordova issue fix this issue for you?

**Comment by BorntraegerMarc** [comment] 2019-01-17 06:52
Hello @csalmi-branch 
Unfortunately I uninstalled the plugin and am using a different one now. So I can't verify whether there's a workaround that works

**Comment by csalmi-branch** [comment] 2019-01-17 16:44
Ok. Thanks for responding and letting us know!

I'm closing this issue due to it being caused by the known issue in cordova. 

If anyone is still experiencing this issue or a new problem arises, please let us know by filling a support ticket or a new github issue.

**Closed by csalmi-branch** 2019-01-17 16:44 UTC
