### ISSUE TITLE
Error with cordova 7.0.0

### ISSUE THREAD

**Issue by nicobytes** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#323] opened 2017-05-04 23:15 UTC
![screen shot 2017-05-04 at 6 12 14 pm](https://cloud.githubusercontent.com/assets/7611944/25728533/61e265a6-30f5-11e7-883f-d919fc55f790.png)

`Failed to restore plugin "branch-cordova-sdk" from config.xml. You might need to try adding it again. Error: Version of installe
d plugin: "es6-promise-plugin@4.1.0" does not satisfy dependency plugin requirement "es6-promise-plugin@^3.0.2". Try --force to
use installed plugin as dependency.`

But I can not downgrade es6-promise-plugin why others plugins need the plugin in 4.1.0

**Comment by ethanneff** [comment] 2017-05-05 18:36
Hello,

Thank you for bringing this to my attention. It looks like the new Cordova 7.0.0 fundamentally changed how apps are generated. A `node_modules` is now added to the root directory of the app which is interfering with Branch's dependencies. I will look into this to hopefully get a solution as soon as possible. I will reach out as soon as I have more information.

Thanks,

**Comment by nicobytes** [comment] 2017-05-09 14:22
but is there any solution? The others plugins work but **branch-cordova-sdk** not work when I try compile.

Thanks a lot!

**Comment by ethanneff** [comment] 2017-05-09 20:38
Hello again,

We are still developing a solution which is compatible with our regression tests. It should be deployed in the next day or two.

Thanks,

**Comment by ethanneff** [comment] 2017-05-09 22:37
Hello,

I have a pull request #325 ready which will add support for Cordova 7.0.0. I am going to run some more tests and maybe clean up some code before releasing it tomorrow.

Thanks,

**Comment by ethanneff** [comment] 2017-05-10 17:36
Hello,

The fix has been submitted. Please update your Branch Cordova SDK to 2.5.17 (https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk).

Thanks,

**Comment by nicobytes** [comment] 2017-05-10 17:43
thanks now I will try

**Comment by nicobytes** [comment] 2017-05-10 20:04
yeah! now all work fine, very thanks @ethanneff

**Closed** 2017-05-10 20:04 UTC
