### ISSUE TITLE
Resume fires multiples times with already handled deeplinks

### ISSUE THREAD

**Issue by geneoes** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#461] opened 2018-05-09 19:28 UTC
Having app **A** and app **B**, using regular old deeplinks (_example: appname//:linkurl_):

1. I open **A** and click a button that redirects to **B**. 
2. **B** got the deeplink as **+non_branch_link_** and I use it to redirect to some page.
3. With **B** now opened, I minimize and maximize **B** and the on the **resume callback** I got again my redirection.

Actual result:
- Every time I resume my app, I got the latest **+non_branch_link**

Expected result:
- Not getting always the **+non_branch_link_** when resuming the app.

Tested on Android (multiple versions) with plugin `3.0.0` and `2.6.0`

**Comment by pixilink** [comment] 2018-06-15 15:42
I am also experiencing this issue. Clicking on the app's custom url scheme in the browser opens the app with the +non_branch_link set as expected and I redirect the user to the appropriate page within the app. If I then navigate to a different page within the app and then switch to a different app and then back again on the resume the +non_branch_link is somehow still set and my user gets redirected again. This also happens if I open a [SafariViewController](https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller) (Chrome Custom Tab) window and then close it which also triggers the resume event.

On a related issue if I click on a branch link within the intercom plugin within the app the resume event is fired but with empty link data and nothing happens as experienced by others see #392. If I switch out of the app and then back again or open an in app browser window and then close it the missing link data from before is now set on resume and the user gets redirected.

**Comment by sequoiaat** [comment] 2018-07-25 05:57
@geneoes  Can you please mention in which platform(Cordova/ionic/PhoneGap) are you trying it?

**Comment by pixilink** [comment] 2018-07-25 06:30
Cordova, Android, Branch 2.5.0

**Comment by geneoes** [comment] 2018-08-01 18:34
Ionic 3 platform!

**Comment by sequoiaat** [comment] 2019-01-25 06:44
@geneoes We've been unable to reproduce the issue. Are you still facing it?

@pixilink Please see a similar issue (like [#392)](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/392) related to in-app click of a deep link to the same app, that was closed https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/394
because this functionality is not supported.

**Comment by csalmi-branch** [comment] 2019-02-13 01:14
Due to the age of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!

**Closed by csalmi-branch** 2019-02-13 01:14 UTC
