### ISSUE TITLE
Sometimes Deep link does not work on app resume.

### ISSUE THREAD

**Issue by sachinkumaram-veoci** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#541] opened 2018-12-20 08:01 UTC
The function parameter for initSession is a function callback for deep link data. Sometimes  Branch.initSession().then((data)  promises not returning any data. In below code, getting alert 'Not received' even data doesn't contain any value.
Platform: Android
`Branch.initSession().then((data) => {
                        if (data['+clicked_branch_link']) {
                            alert('Received');
                        } else {
                            alert('Not received');
                        }
                    });`

**Comment by sequoiaat** [comment] 2018-12-22 01:44
@sachinkumaram-veoci  We were unable to reproduce it .  Any specific conditions if you would specify which will enable us to reproduce this?  Also this could happen if there are network latency issues.

**Comment by sachinkumaram-veoci** [comment] 2019-01-07 09:16
@sequoiaat I have checked, there is no network latency issue. Sometimes it works fine sometimes not.

**Comment by sachinkumaram-veoci** [comment] 2019-01-07 09:22
@sequoiaat This issue has been aries only if app is already open in background, othewise it work fine if app is kill and open directly through deep link.

**Comment by sequoiaat** [comment] 2019-01-08 12:44
@sachinkumaram-veoci Could you please check if you are setting Branch.disableTracking(true) before calling Branch.InitSession?

**Comment by sachinkumaram-veoci** [comment] 2019-01-08 15:25
@sequoiaat No, we are not setting Branch.disableTracking(true) .

**Comment by sachinkumaram-veoci** [comment] 2019-01-10 06:52
@sequoiaat I have checked and found that due to **phonegap-nfc** plugin it was conflicting. Any possible solution ?

**Comment by sequoiaat** [comment] 2019-01-15 05:54
@sachinkumaram-veoci We're trying to reproduce the issue with phonegap-nfc plugin. We will keep you updated shortly.

**Comment by sequoiaat** [comment] 2019-01-16 06:32
@sachinkumaram-veoci We reproduced the issue with phonegap-nfc plugin. We are doing some more tests related to inter-operability and we will update you shortly.

**Comment by sequoiaat** [comment] 2019-01-19 05:55
@sachinkumaram-veoci We realized that the phonegap-nfc plugin is incompatible with Branch. Please see our documentation at 
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-incompatible-plugins
Sorry for not having alerted you earlier on this!

**Comment by csalmi-branch** [comment] 2019-01-25 01:11
Since this is a known problem (incompatible plugin) I am closing this issue. If you have any further concerns or issues, please reach out to our support team (https://support.branch.io/support/home) or open a new github issue.

**Closed by csalmi-branch** 2019-01-25 01:11 UTC
