### ISSUE TITLE
Android error on cold start when disabling trackings

### ISSUE THREAD

**Issue by Morathil** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#455] opened 2018-05-04 13:21 UTC
Hey, we receive the following error message on android on app cold start from `initSession` when calling `disableTracking(true)` before:

```
Trouble initializing Branch. Tracking is disabled.
Requested operation cannot be completed when tracking is disabled
```

As a result we do not receive our deeplink data.
Calling `initSession` after an app resume works fine and we receive our deeplink data.
iOS works fine for cold start and app resume.

Can you please help us with this issue?

**Comment by ethanneff** [comment] 2018-05-08 15:50
Hello,

Thank you for bringing this to my attention. I was able to reproduce it. It looks to be an issue with our underlying Android SDK. I am escalating this internally to get a fix as soon as possible. 

I'll keep you updated.

**Comment by ethanneff** [comment] 2018-05-08 17:28
Hello again,

After doing some more tests and coordinating with our mobile team, what you are experiencing is the intended behavior. 

works (app terminated)
1) set `Branch.disableTracking(true)`
2) install the app
3) terminate the app
4) click a deep link
5) app opens with data

works (app backgrounded)
1) set `Branch.disableTracking(true)`
2) install the app
3) background the app
4) click a deep link
5) app opens with data

fails (app store install simulation)
1) set `Branch.disableTracking(true)`
2) click a deep link
3) install the app
4) app opens with no  data

This behavior is the same for both iOS and Android. If you want to get the deep link data after an App Store installation, you cannot default `Branch.disableTracking(true)`. This assumes the user does not want to be tracked from the beginning - which is why there is no data. An alternative solution is to:
- default `Branch.disableTracking(false)`
- show a dialog to a user to determine if they want to be tracked or not
- set `Branch.disableTracking(true)` based on that user's response
- handle the initial deep link data accordingly 

This will allow you to capture the initial install data within your app, and allow all future request to be up to the decision of the user.

I apologize for the confusion. We are still working out on the best practices that developers should use with this feature.

**Comment by Morathil** [comment] 2018-05-09 13:12
Hey, thanks for your reply!

It's true that the behaviour is the same on iOS and Android.

But we're a bit confused as the Android and iOS [Branch documentation](https://github.com/BranchMetrics/android-branch-deep-linking#enable-or-disable-user-tracking) says:

```
This will prevent any Branch requests from being sent across the network, except for the
case of deep linking. If someone clicks a Branch link, but has expressed not to be tracked,
we will return deep linking data back to the client but without tracking information captured.
```

what is the opposite of what you commented: `This assumes the user does not want to be tracked from the beginning - which is why there is no data.`

The quote from the Android/iOS Branch documentation would make perfectly sense to us and that's what we expected the behaviour to be and what we would actually need.

Can you please clarify this to us?

The alternative solution would not work for us as we need the deeplink data before asking the user if he wants to be tracked or not. Also we assume that when we call `Branch.disableTracking(false)` and `Branch.initialize()` afterwards (before asking for the user consent) that you would track something with the `initialize` call on your side as tracking is enabled? That would not be GDPR compliant? 🤔 

Also we don't understand the first example above. Setting `Branch.disableTracking(true)` before installing the app makes no sense to us.

What I just tried:

1. Install the app
2. Open the app
3. Set Branch.disableTracking(true)
4. InitializeBranch
5. Terminate app
6. Open app via deeplink
7. Set Branch.disableTracking(true)
8. InitializeBranch
9. No deeplink data received

**Comment by sirflo** [comment] 2018-05-11 13:40
We understand the need for tracking in order to be able to provide deep linking across app installs. Deep links should be resolved correctly when the app is already installed even when tracking has never been enabled (as cited your examples).

However, in our testing the deep link is not resolved correctly for installed but terminated apps when tracking is disabled. It only works when the app is running in the background. We experience this on Android as well as iOS (with the Cordova plugin).

This appears to be a bug. Can you please look into this as we're under pressure to get everything ready as soon as possible for GDPR. Thanks a lot!

**Comment by steeltree** [comment] 2018-06-11 00:37
Is there any update on this issue? We are experiencing the same problem using version 3.0.0 of the plugin. 

Setting Branch.disableTracking(true) results in no deep link data if the app is terminated and then opened again via a deep link. If the app is started (running in the background) deep links work as expected and deep link data is received.

Any help would be much appreciated!

**Comment by csalmi-branch** [comment] 2019-01-28 22:37
@steeltree and @sirflo, are either of you still experiencing this issue? @sequoiaat is investigating the issue, and any new information you might have to add would be helpful.

**Comment by sequoiaat** [comment] 2019-01-29 07:12
We were unable to reproduce this issue on Android phone (We tried with multiple Android phones). However we observed this issue on the emulator (on Windows). Can you please comment?

**Comment by csalmi-branch** [comment] 2019-02-13 01:19
Due to the age of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!

**Closed by csalmi-branch** 2019-02-13 01:19 UTC

**Comment by levyschiavetti** [comment] 2021-12-20 14:17
I'm not sure why this issue is closed since the problem still exists. I'm experiencing it right now

**Comment by vasa137** [comment] 2024-05-19 15:39
I still face this issue - I cannot initialize branch since I want tracking to be disabled.
