### ISSUE TITLE
Integrate with Eddy Verbruggen's plugin

### ISSUE THREAD

**Issue by dangreenisrael** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#27] opened 2015-11-09 09:19 UTC
Eddy Vebruggen has made a fantastic plugin for opening cordova apps that works AMAZINGLY with Branch.  I was just about to finally give up on branch (I had removed all the code from my app) when I decided to give it one last attempt.

I think that this plugin should either
a) Directly integrate his plugin
b) Tell people to install it first in the instructions

https://github.com/EddyVerbruggen/Custom-URL-scheme

**Comment by maxrevilo** [comment] 2016-03-14 21:12
Yea I am using the same plugin to register the URL Scheme of my own app, should be mentioned in the instructions.

**Comment by renesansz** [comment] 2016-03-23 06:48
Hello @dangreenisrael , you could implement this first on your own.
Then if it works well, you could submit a PR suggesting to have this plugin integrated with our plugin.
We'll review the PR and decide, if we see it fit to have this plugin necessary.

Thanks

**Comment by malua** [comment] 2016-06-13 12:59
I am also trying to get both these plugins working.
our app already uses the Custom URL scheme plugin and handles incoming links with handleOpenURL(url). 

in the config.xml I got:
```
<gap:plugin name="cordova-plugin-customurlscheme" source="npm">
	  <param name="URL_SCHEME" value="myapp" />
</gap:plugin>
```

do i need to keep that even if i add the branch plugin:
```
<gap:plugin name="branch-cordova-sdk" source="npm" version="2.1.2">
		<param name="BRANCH_KEY" value="***"/>
		<param name="URI_SCHEME" value="myapp" />
</gap:plugin>
```

which of the two should i be using? if keep the config from verbruggens plugin, DeepLinkHandler is never called. if I remove it, only DeepLinkHandler is called. even if its not a branch deeplink. shouldn't that call NonBranchLinkHandler(data)? any help is much appreciated!

**Comment by aaustin** [comment] 2016-06-13 16:27
Hey @malua - Both do basically the same thing but it sounds like our app is not properly calling NonBranchLinkHandler if it's not being triggered with non-Branch links. In theory, you shouldn't need to include Eddy's if you use Branch, but that's only if we're properly returning your non-Branch URI schemes.

Let me understand the context so that we can reproduce.
- Which OS are you testing on?
- You're saying that when you remove Eddy's and only have Branch, you trigger a non-Branch URI like `myapp://` and it doesn't call NonBranchLinkHandler?

Longer term, we should make it so that we don't clobber Eddy's settings.

**Comment by malua** [comment] 2016-06-14 09:16
Thanks for the quick response. I have a phonegap app for ios and android. But atm I am testing on android. 
When I type `myapp://` in the webbrowser the app opens and DeepLinkHandler is called. The parameter has this information: `Object {+is_first_session: false, +clicked_branch_link: false}`. The same thing happens if I open an old deeplink, where the information is encoded in the url. But since DeepLinkHandler only receives that object and not the full url I can't properly decode it.
And NonBranchLinkHandler never gets called. It's defined as a global function just next to DeepLinkHandler. Its copy and paste from the readme and i checked for spelling mistakes etc.

**Comment by aaustin** [comment] 2016-06-15 03:33
Interesting. Let me see what I can come up with here. I understand how frustrating that must be.

**Comment by aaustin** [comment] 2016-06-20 18:09
Hey @malua - I fixed up this code path in this PR, where we'll pass in the deep link URL if it's not a Branch link: https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/pull/155

Would love if you would try it out and let me know if it helps!

**Comment by malua** [comment] 2016-06-24 11:28
I am sorry but I don't really know how to integrate the changes. as it's not merged yet, the changes won't be on npm right? I tried with the newest version but it's the same as before.

**Comment by aaustin** [comment] 2016-06-24 15:06
Ah - ok. I'll ask someone else to help me test it and merge it in. I'm pretty confident in the changes.

**Comment by aaustin** [comment] 2016-06-25 01:28
Hey @malua - I've updated public repos. Whenever it's not a Branch link the, deep link URL will be passed back via the `NonBranchLinkHandler` in a dictionary:
```
{
  error: "Not a Branch link!",
  url: "<deep link url>"
}
```

**Comment by aaustin** [comment] 2016-06-25 01:30
Will close this as it's no longer a direct issue. The library should act as a full replacement for Eddy's but also properly handle Branch links.

**Closed by aaustin** 2016-06-25 01:30 UTC
