### ISSUE TITLE
iOS doesn't generate branchUniversalObj.generateShortUrl

### ISSUE THREAD

**Issue by JoseETeixeira** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#477] opened 2018-07-03 12:35 UTC
On android the code below works fine:

`
           platform.ready().then(() => {
                this.init();
            });
    
            platform.resume.subscribe(() => {
                this.init();
            });

init(): Promise<{ link: DeeplinkData } | null> {
        // only on devices. this is here for testing in browser.
        if (!this.platform.is('cordova')) {
          return;
        }
    
        this.Branch = window['Branch'];
        if (!this.Branch) {
          const msg = 'Branch.io cordova plugin not found';
          console.error(msg);
          return Promise.resolve(null);
        }
    
        return this.Branch.initSession(data => {
          if (data['+clicked_branch_link']) {
            // read deep link data on click
            //const linkData = this.parseDeepLinkData(data);
            //this.events.publish('deeplink:opened', { link: linkData });
                this.viewItem(data);
               
            });

          } else {
            console.log('Branch init callback ', data);
          }
        });
      }

...

    //--------------------------------------------------------------------------------
    share(img, titulo, preco, validade, id){
        // create a branchUniversalObj variable to reference with other Branch methods
        this.createUniversalBranch(img, titulo, preco, validade, id);
       
        
    }

    createUniversalBranch(img, titulo, preco, validade, id){

        var loader = null;

        if (!loader) {
            loader = this.loading.create({
                spinner: 'dots',
                cssClass: 'custom-loader',
                content: "<h4><img src='assets/img/logo_loader.png'>" + "Por favor, aguarde..." + "</h4><br/><p>" + "Gerando Link" + "</p>",
            });
        }

        var properties = {
            canonicalIdentifier: id,
            canonicalUrl: "https://mycanonicalurlishere.com",
            title: titulo,
            contentImageUrl: "https://myimgurlishere.com",
            contentIndexingMode: "public",
            currency: 'BRL',
            price: preco,
            contentMetadata: {
              titulo: titulo,
              preco: preco,
              img: img,
              validade: validade,
              id:id
            }
        };
        if (!this.Branch) {
            const msg = 'Branch.io cordova plugin not found';
            console.error(msg);
            return null;
        }
        loader.present();
        console.log("Entrou na função");
        var branchUniversalObj = null;
        this.Branch.createBranchUniversalObject(properties).then(function(res) {
            console.log('criei universal obj: ' + JSON.stringify(res));
            branchUniversalObj = res;
            return branchUniversalObj;
        })
        .then(function(res){
            console.log('recebi universal obj: ' + JSON.stringify(res));
            branchUniversalObj
            .generateShortUrl({}, {})
            .then(function(res) {
                console.log("Gerei short url:  " + JSON.stringify(res.url));
                loader.dismiss();
                branchUniversalObj.showShareSheet({}, {}, message);
            })
            .catch(function(err) {
                console.error("Error: " + JSON.stringify(err));
                return null;
            });
            
        })
        .catch((err) => {
            console.error(err.message); // something bad happened
            return null;
        });

    }
`

however, on iOS the console outputs:

> 2018-07-03 09:32:00.400534-0300 comOferta[309:24025] Entrou na função
2018-07-03 09:32:00.446904-0300 comOferta[309:24025] criei universal obj: {"message":"createBranchUniversalObject Success","instanceId":0}
2018-07-03 09:32:00.447156-0300 comOferta[309:24025] recebi universal obj: {"message":"createBranchUniversalObject Success","instanceId":0}
2018-07-03 09:32:00.447676-0300 comOferta[309:24025] -[__NSCFNumber length]: unrecognized selector sent to instance 0xb0000000001188f3
2018-07-03 09:32:00.451571-0300 comOferta[309:24025] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[__NSCFNumber length]: unrecognized selector sent to instance 0xb0000000001188f3

I've tried changing the createUniversalBranch function to:

`
...

.then(function(res){
            console.log('recebi universal obj: ' + JSON.stringify(res));
            branchUniversalObj = res;
            branchUniversalObj.generateShortUrl({}, {});
            return branchUniversalObj;
        })
        .then(function(res) {
            console.log("Gerei short url:  " + JSON.stringify(res));
            branchUniversalObj = res;
            loader.dismiss();
            return branchUniversalObj;
            //branchUniversalObj.showShareSheet({}, {}, message);
        })

...

`

but still the same error occurs. Any insights/ fixes?

**Comment by paulstelzer** [comment] 2018-08-31 14:40
Did you get it work ? I tried today and for me it's still not working!

**Comment by sequoiaat** [comment] 2018-10-05 20:21
@JoseETeixeira  We tried to reproduce this but  we are unable to see the issue. The version we tried on is as follows 

Branch-cordova-sdk: 3.1.0
Cordova iOS version: 4.5.4
Ionic version: 3.20.0
Cordova version: 8.0.0
Node: 8.11.1
Npm: 5.6.0

this is the code we used 

 const Branch = window["Branch"];
    // only canonicalIdentifier is required
    var buo = {
      canonicalIdentifier: "content/123",
      canonicalUrl: "https://example.com/content/123",
      title: "Content 123 Title",
      contentDescription: "Content 123 Description " + Date.now(),
      contentImageUrl: "http://lorempixel.com/400/400/",
      price: 12.12,
      currency: "GBD",
      contentIndexingMode: "private",
      contentMetadata: {
        custom: "data",
        testing: 123,
        this_is: true
      }
    };
 
    Branch.createBranchUniversalObject(buo).then(function (res) {
      // optional fields
      var analytics = {
        channel: "facebook",
        feature: "onboarding",
        campaign: "content 123 launch",
        stage: "new user",
        tags: ["one", "two", "three"]
      };
 
      // optional fields
      var properties = {
        $desktop_url: "http://www.example.com/desktop",
        custom_string: "data",
        custom_integer: Date.now(),
        custom_boolean: true,
        custom_array: [1, 2, 3, 4, 5],
        custom_object: { random: "dictionary" }
      };
 
      res.generateShortUrl(analytics, properties).then(function (res) {
        alert('Response: ' + JSON.stringify(res.url))
      }).catch(function (err) {
        alert('Error: ' + JSON.stringify(err))
      });
    });

**Comment by csalmi-branch** [comment] 2019-01-08 23:17
@JoseETeixeira Are you still experiencing this issue? If so, could you provide us with more information about what version you are using?

**Comment by csalmi-branch** [comment] 2019-01-29 00:05
Due to the age of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!

**Closed by csalmi-branch** 2019-01-29 00:05 UTC
