### ISSUE TITLE
On ionic 2, does initSession() need to be called onResume?

### ISSUE THREAD

**Issue by chanphillip** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#268] opened 2016-12-30 07:00 UTC
In the docs, some places say it's needed and some do not.
Is initSession() suppose to be called every onResume?

**Comment by renesansz** [comment] 2016-12-30 14:45
@chanphillip ,
Hello, I haven't tried using the plugin w/ Ionic 2. Can you please elaborate your question?
As far as I know, you always needed to initialize the session every time the device starts so that you can use the Branch methods, in Cordova it should be initialize on `deviceReady`. See [doc](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#initialize-branch-features)

**Comment by ethanneff** [comment] 2017-01-06 01:37
Hello @chanphillip,

The reason why `initSession()` is called within `resume` and `deviceready` is because of scenarios on some Android devices where deep link data will not pass into the app on open. 

When testing, this issue appeared to be isolated with `Phonegap` and `Cordova` builds. I have not been able to replicate this Android issue with `Ionic`, which is why the documentation only contains `Branch.initSession()` within `$ionicPlatform.ready(function()` for Ionic 1 and `   platform.ready().then(() =>` for Ionic 2.

If you notice that Branch deep link data is not being passed within your `Ionic 2` app, please reach out and we will add your use case to our regression tests.

Best,

**Comment by ethanneff** [comment] 2017-01-17 18:12
@chanphillip I am closing this ticket, feel free to reach out if you are still experiencing issues.

**Closed by ethanneff** 2017-01-17 18:12 UTC
